### PR TITLE
fix(near): Dynamic deposit amounts

### LINKED ISSUE #132: Fix deposit amounts
Some of the deposit values [here](https://github.com/Near-One/bridge-sdk-js/blob/0b12d7cc88edabb0c60a59b284038d81c72290fc/src/clients/near.ts#L49C1-L56C11) aren't correct.

```ts
const DEPOSIT = {
  LOG_METADATA: BigInt(2e23), // 0.2 NEAR
  DEPLOY_TOKEN: BigInt(4e24), // 4 NEAR
  BIND_TOKEN: BigInt(2e23), // 0.2 NEAR
  SIGN_TRANSFER: BigInt(5e23), // 0.5 NEAR
  INIT_TRANSFER: BigInt(1), // 1 yoctoNEAR
  FIN_TRANSFER: BigInt(1), // 1 yoctoNEAR
} as const
```

Should be replaced with

```ts
const DEPOSIT = {
  LOG_METADATA: BigInt(1), // 1 yoctoNEAR
  DEPLOY_TOKEN: BigInt(3007710000000000000000000), // 3,00771  NEAR
  BIND_TOKEN: BigInt(5370000000000000000000), // 0,00537 NEAR 
  SIGN_TRANSFER: BigInt(1), // 1 yoctoNEAR
  INIT_TRANSFER: BigInt(1), // 1 yoctoNEAR
  FIN_TRANSFER: BigInt(580000000000000000002), // 0,00058 NEAR
} as const
```

The deposit amounts can be retrieved from the contract view methods for these actions `DEPLOY_TOKEN`, `BIND_TOKEN`, `FIN_TRANSFER`

### PR DESCRIPTION
**Pull request by r-near**
Use dynamic attached deposit amounts instead of hardcoding the values. Closes #132

### CODE REVIEW

File: src/clients/near-wallet-selector.ts [hunk 1]
```diff
@@ -185,6 +182,13 @@ export class NearWalletSelectorBridgeClient {
     }
     const serializedArgs = DeployTokenArgsSchema.serialize(args)
 
+    // Retrieve required deposit dynamically for deploy_token
+    const deployDepositStr = await this.viewFunction({
+      contractId: this.lockerAddress,
+      methodName: "required_balance_for_deploy_token",
+    })
+    const deployDeposit = BigInt(deployDepositStr)
```
Comment (kiseln) [inline src/clients/near-wallet-selector.ts:190]: What is the difference between `deployDepositStr` and what we pass to the function call (`deployDeposit.toString()`)?

File: src/clients/near-wallet-selector.ts [hunk 2]
```diff
@@ -256,7 +260,19 @@ export class NearWalletSelectorBridgeClient {
...
+
     const wallet = await this.selector.wallet()
+    const accounts = await wallet.getAccounts()
+    const accountId = accounts[0].accountId
+
+    // Retrieve required deposit dynamically for bind_token
+    const bindDepositStr = await this.viewFunction({
+      contractId: this.lockerAddress,
+      methodName: "required_balance_for_bind_token",
+      args: { account_id: accountId },
```
Comment (kiseln) [inline src/clients/near-wallet-selector.ts:272]: I don't see `account_id` arg for this function https://github.com/Near-One/omni-bridge/blob/main/near/omni-bridge/src/storage.rs#L195

File: src/clients/near-wallet-selector.ts [hunk 3]
```diff
@@ -549,6 +565,17 @@ export class NearWalletSelectorBridgeClient {
...
 
     const wallet = await this.selector.wallet()
+    const accounts = await wallet.getAccounts()
+    const accountId = accounts[0].accountId
+
+    // Retrieve required deposit dynamically for fin_transfer
+    const finDepositStr = await this.viewFunction({
+      contractId: this.lockerAddress,
+      methodName: "required_balance_for_fin_transfer",
+      args: { account_id: accountId },
```
Comment (kiseln) [inline src/clients/near-wallet-selector.ts:575]: Don't see the arg https://github.com/Near-One/omni-bridge/blob/main/near/omni-bridge/src/storage.rs#L181

Comment (r-near) [reply src/clients/near-wallet-selector.ts]: Weird, I had this in the other view calls too, thanks!

File: src/clients/near-wallet-selector.ts (hunk 1 above)
Comment (r-near) [reply src/clients/near-wallet-selector.ts]: No difference, just me being silly 🤣

**Review by kiseln — APPROVED** [review]
